setwd("C:/Users/Przemek/Documents/INFO324/assignment2")
#Exercise 1
#Part 2
pdata<-read.csv("pdata.csv", header=TRUE)
liniowy<-lm(pdata$y~pdata$x)
plot(pdata$x,pdata$y, xlab="x", ylab="y")
title( main="Real values of x and y & prediction of linear model", cex.main=0.9)
help(plot)
summary(liniowy)
abline(liniowy, col=2)


#Exercise 2
data(mtcars)
head(mtcars)
auta<-lm(formula = mpg ~ wt + qsec + am+carb+gear+vs+drat+hp+disp+cyl, data = mtcars)
summary(auta)
step(auta)
auta<-data.frame(auta$fitted.values)
plot(mtcars[,1], auta[,1], main="Real and predicted value of mpg generated by linear model",xlab="Real values", ylab="Predicted values")
abline(10,10, col=2, lwd=2)
head(mtcars)
for(i in c(2,8,9,10,11))
{
  sort(mtcars[,i])
  mtcars[,i]<-as.factor(mtcars[,i]) 
}
help(rpart)
mtcars$cyl
drzewocar<-rpart(mpg~cyl+disp+hp+drat+wt+qsec+vs+am+gear+carb, data=mtcars)
summary(drzewocar)
par(mfrow = c(1,1), xpd = NA)
plot(drzewocar,branch=0,compress=TRUE)
text(drzewocar, use.n=TRUE)
plot(drzewocar, branch=0,compress=TRUE,  main="Decision Tree for the car test")
text(drzewocar, pretty=0, use.n=TRUE, fancy=FALSE, all=FALSE, cex=0.75, fwidth=0.25, xpd=TRUE)
data.frame(drzewocar)
drzewopred<-predict(drzewocar)
drzewopred<-data.frame(drzewopred)
drzewopred
plot(mtcars[,1],drzewopred[,1], main="Real and predicted value of mpg generated by decision tree", xlab="Real values", ylab="Predicted values")

#Exercise 3
pdata <- read.csv('pdata.csv',header=TRUE)

#part1
head(pdata)
help(hist)
hist(pdata$y, col=3, xlab='y')
summary(pdata)

#Part2
liniowy<-lm(pdata$y~pdata$x-1)
plot(pdata$x,pdata$y, xlab="x", ylab="y")
title( main="Real values of x and y & prediction of linear model", cex.main=0.9)
help(plot)
summary(liniowy)
abline(liniowy, col=2, lwd=2)

#Part3
xd2=pdata$x^2
xd3=pdata$x^3
ax<-cbind(pdata,xd2,xd3)
liniowy3<-lm(y~x+I(x^2)+I(x^3), pdata)
summary(liniowy3)
liniowy2<-lm(y~x+I(x^3), pdata)
summary(liniowy2)
plot(pdata$x,pdata$y, xlab="x", ylab="y")
xvec <- seq(from=-5,to=5,by=0.01)
help(seq)
class(pdata)
anova(liniowy3,liniowy2)

title(main="Comparison of fittnes between linear and non-linear model", cex.main = 0.9)
help(legend)
lines(pdata$x,predict(liniowy3), col=7, lwd=2)
legend(-3,250,c("Model1", "Model2"), col=c(2,7), lty=c(1,1), lwd=c(3,3), cex=0.6, title="Legend")

r=rstandard(liniowy)
lf<-fitted(liniowy)
r=rstandard(liniowy3)
lf<-fitted(liniowy3)
plot(pdata$x, r,xlab="x", ylab="standarized residuals")
abline(h=0)
plot(lf,r,xlab="Fitted values", ylab='Stamdarized residuals')
abline(h=0)
qqnorm(r,xlab="N(0,1) quantiles ", ylab="Standarized residuals", main="Linear model")
abline(0,1, col=2, lwd=2)

AIC(liniowy)
AIC(liniowy2)
  AIC(liniowy3)

#Part 2 Exercise 4
un.scale.data <- function(data.set,attr.scale, attr.center)
{
  data.set <- t(apply(data.set,1,function(x) x * attr.scale))
  t(apply(data.set,1,function(x) x + attr.center))
}


library(neuralnet)
library(MASS)

Bostoni<-read.csv('Boston.csv', header=TRUE)

Boston2<-scale(Bostoni)

scaled.scale <- attr(Boston2,"scaled:scale")
scaled.center <- attr(Boston2,"scaled:center")

#unscale function

i=2
#Ordering variables and transforming into data.frame
#Boston2<-data.frame(Boston2)
#orBoston <- Boston2[order(Boston2$medv),]
net.b3<-neuralnet(medv ~ ptratio+tax+rm+nox+indus+crim, data = Boston2, hidden=i)
net.b3 <- neuralnet(medv ~ crim+indus+nox+rm+tax+ptratio,data = Boston2,hidden=i)

n2 <- neuralnet(medv ~ rm+tax+ptratio+crim+indus+nox ,data = b.s,hidden=i)
nn <- neuralnet(medv ~ crim+indus+nox+rm+tax+ptratio,data = b.s,hidden=hidden)
nn
n1
n2
net.b3
scBostzap<-Boston2

#Transforming other variables into their median apart from rm and medv
#for(i in seq(from= 1, to= 3, by=1))
#{
 # scBostzap[,i]<-rep(median(scBostzap[,i]),length.out=100)
#}
scBostzap<-apply(Boston2,2,function(x) rep(median(x),100))
#for(i in seq(from= 5, to= 6, by=1))
#{
#  scBostzap[,i]<-rep(median(scBostzap[,i]),length.out=100)
#}
#RM variable 
scBostzap[,4]<-seq(from=min(Boston2[,4]), to=max(Boston2[,4]), length.out=100)

#ANN
#par(mfrow=c(1,1))
net.pred2 <- compute(net.b3, scBostzap[,1:6])
net.pred2$net.result


net.b3
# Computation

head(net.pred2)
head(net.pred2[[2]])
# Unscalling

net.pred.unscaled <- un.scale.data(net.pred2$net.result,scale.scale[7],scale.center[7])
rmorig <- un.scale.data(scBostzap[,4],scale.scale[4],scale.center[4])
net.pred.unscaled<-net.pred.unscaled[order(net.pred.unscaled)]
#Plot itself
plot(Bostoni$rm,net.pred.unscaled, xlab="Number of rooms", ylab="Median price for the room predicted by ANN", main=paste("Response curve for " , i ,"hidden nodes") )

summary(Bostoni)

pairs(Bostoni)
?mtcars
net.b1<-neuralnet(medv ~ ptratio+tax+rm+nox+indus+crim,data = scBostzap)
net.b1
plot(net.b1)  
net.b3<-neuralnet(medv ~ ptratio+tax+rm+nox+indus+crim,data = scBostzap,hidden=3)
net.b3
plot(net.b3)	
net.b5<-neuralnet(medv ~ ptratio+tax+rm+nox+indus+crim,data = scBostzap,hidden=5)	
net.b5
plot(net.b5)







